name: Build

on: [pull_request, workflow_dispatch]

env:
  BUILD_TYPE: Release
  MAKE_THREAD_NUM: 16

jobs:
  build:
    strategy:
      matrix:
        os: ['windows-latest']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j ${{env.MAKE_THREAD_NUM}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
